version: '3.8'

services:
  app:
    container_name: url-shorter
    build: .
    ports:
      - '8080:8080'
    environment:
      - DB_USER={DB_USER}
      - DB_PASSWORD={DB_PASSWORD}
      - DB_CONNECTION=${DB_CONNECTION}
    depends_on:
      - db
    networks:
      - java-network

  db:
    image: postgres:17
    container_name: url-shorter-db
    environment:
        - POSTGRES_DB=db_urls
        - DB_USER={DB_USER}
        - DB_PASSWORD={DB_PASSWORD}
    ports:
      - '5431:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - java-network

volumes:
  pgdata:

networks:
  java-network:
    driver: bridge